### PR TITLE
Easy case branch

### PR DESCRIPTION
**Pull request by EasyCase**
hello,I am EasyCase,I Create a New Branch.

### CODE REVIEW

**Comment by EasyCase** [comment]
Thanks for your work.But I Dislike this idear.

**Comment by EasyGoGo** [comment]
thanks for your work,but i dislike this iear.

**Comment by EasyGoGo** [comment]
- [X] 编写代码
- [ ] 编写所有测试程序
- [ ] 为代码编写文档

**Comment by EasyGoGo** [comment]
> hello,I am EasyCase,I Create a New Branch.

@EasyGoGo 

- [ ] 

1. 

- 

> 

> 

> `[](www.baidu.com)`

**Pull request merged**
